SET SERVEROUTPUT ON;
DECLARE
NAME VARCHAR(30);
JOB VARCHAR(30);
EID NUMBER;
CURSOR C(E NUMBER) IS
SELECT FIRST_NAME,JOB_ID,EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID > E;

BEGIN

FOR NC IN C(200) LOOP
DBMS_OUTPUT.PUT_LINE(NC.EMPLOYEE_ID ||'    '||NC.FIRST_NAME ||'    '|| NC.JOB_ID);
END LOOP;
END;
