SET SERVEROUTPUT ON;

DECLARE
EMP EMPLOYEES%ROWTYPE;

BEGIN
SELECT * INTO EMP FROM EMPLOYEES WHERE EMPLOYEE_ID=200;
DBMS_OUTPUT.PUT_LINE(EMP.FIRST_NAME ||' '|| EMP.EMPLOYEE_ID);
DBMS_OUTPUT.PUT_LINE(EMP.HIRE_DATE);

END;
