CREATE TRIGGER TR
BEFORE INSERT OR UPDATE OR DELETE ON NETFLIX
FOR EACH ROW
ENABLE

DECLARE
V_USER VARCHAR(20);

BEGIN
SELECT USER INTO V_USER FROM DUAL;

IF INSERTING THEN
DBMS_OUTPUT.PUT_LINE('ONE ROW INSERTED BY '|| V_USER);

ELSIF UPDATING THEN
DBMS_OUTPUT.PUT_LINE('ONE ROW UPDATED BY'||V_USER);

ELSIF DELETING THEN
DBMS_OUTPUT.PUT_LINE('ONE ROW DELETED BY'|| V_USER);
END IF;
END;
/

SET SERVEROUTPUT ON;
INSERT INTO NETFLIX VALUES('STRANGER THINGS');
UPDATE NETFLIX SET SERIES = 'PEAKY BLINDER' WHERE SERIES='STRANGER THINGS';
DELETE FROM NETFLIX WHERE SERIES ='PEAKY BLINDER';
SELECT * FROM NETFLIX;
